### ISSUE TITLE
Epic: Open source the angeleno-my-account-flutter

### ISSUE THREAD

**Issue by technima** [CityOfLosAngeles/angeleno-account-my-account#10]
#### SNow
[INC0610445](https://cityoflaprod.service-now.com/nav_to.do?uri=incident.do?sys_id=07e96e3187dc7510f2ae97583cbb35e4)

## Development
```[tasklist]
### Tasks
- [ ] https://github.com/CityOfLosAngeles/angeleno-my-account-flutter/issues/12
- [ ] https://github.com/CityOfLosAngeles/angeleno-my-account-flutter/issues/14
- [ ] https://github.com/CityOfLosAngeles/angeleno-my-account-flutter/issues/16
- [ ] https://github.com/CityOfLosAngeles/angeleno-my-account-flutter/issues/17
- [ ] https://github.com/CityOfLosAngeles/angeleno-my-account-flutter/issues/18
- [ ] https://github.com/CityOfLosAngeles/angeleno-my-account-flutter/issues/13
- [x] Enable Github Advanced Security
- [ ] https://github.com/CityOfLosAngeles/angeleno-my-account-flutter/issues/68
- [ ] https://github.com/CityOfLosAngeles/angeleno-my-account-flutter/issues/69
- [x] Enable Wazuh
- [x] Add Topics
- [ ] https://github.com/CityOfLosAngeles/angeleno-my-account-flutter/issues/76
- [ ] https://github.com/CityOfLosAngeles/angeleno-my-account/issues/77
- [x] Rename Branches to Match Deployment Environments
```

## To-Do when Repository is made Public
```[tasklist]
### Tasks
- [x] Uncomment Sarif File in GH Action
- [x] Make sure Private Vulnerability Reporting is Enabled
- [x] Make sure Security Policy is Enabled
- [x] Enable CodeCov
- [x] Turn on secret scanning
- [ ] Security Team asks for WAF for environments
```

**Comment by cbhernan** [comment]
Added 2nd task list for To-Do's when repo is made public. Actions items come from #20 and #30
