### ISSUE TITLE
Flutter Design and Branding Guidelines

### ISSUE THREAD

**Issue by cbhernan** [CityOfLosAngeles/angeleno-account-my-account#23]
### Problem
We don't currently have a central location to track all design decisions we make, so this should be used as such.

### Background info
We're using Flutter with Material Design 3 - there are multiple styles when it comes to text inputs, buttons, navigation, etc, so we need to nail down what we want to go with.

### Proposed Solution

**This list is not final**, and we will be adding more elements as we come across them
```[tasklist]
### Tasks
- [ ] Decide on main Swatch Color
- [x] Decide on what we want Text Inputs to look like
- [x] Decide on what we want Buttons to look like
```

### Snow Incident
[INC0621352](https://cityoflaprod.service-now.com/nav_to.do?uri=incident.do?sys_id=e4326de287b8751008a364ec0ebb35fc) - Theme swatch pending response from web team

**Comment by nickchaula** [comment]
### Text input and button decision (subject to change):

**Buttons:**
- buttons_style = pill
- button_border_weight = 1px  (For buttons that are not color filled)

**Text Input:**
- inputs_style = rounded ("Squircle")
- input_border_weight  = 1px
- input_border_radius  = 5

**Widget Containers:**
- style = rounded ("Squircle", but more rounded than the text inputs)
- widget_corner_radius = 25px
- widget_border_weight = 0

**Do not show shadows for buttons/containers.**

For reference: https://flutter.github.io/samples/web/material_3_demo/ and our Auth0 playgrounds/dev

![image](https://github.com/CityOfLosAngeles/angeleno-my-account-flutter/assets/49528463/a9045941-3f7b-425f-b52c-6fb673c710b7)
